/**
 * Username Generator Utility
 *
 * Generates unique usernames from Supabase UID for automatic profile creation
 */

/**
 * Generate a username from Supabase UID
 * Format: user_[first8chars] (e.g., user_a1b2c3d4)
 */
export function generateUsernameFromUID(uid: string): string {
  // Remove hyphens and take first 8 characters
  const cleanUID = uid.replace(/-/g, "");
  const shortUID = cleanUID.substring(0, 8);

  return `user_${shortUID}`;
}

/**
 * Generate a slug from Supabase UID (same as username for initial creation)
 * Format: user_[first8chars] (e.g., user_a1b2c3d4)
 */
export function generateSlugFromUID(uid: string): string {
  return generateUsernameFromUID(uid);
}

/**
 * Validate that a generated username follows the correct pattern
 */
export function isValidGeneratedUsername(username: string): boolean {
  const pattern = /^user_[a-f0-9]{8}$/;
  return pattern.test(username);
}

/**
 * Check if a username was auto-generated (vs user-created)
 */
export function isAutoGeneratedUsername(username: string): boolean {
  return isValidGeneratedUsername(username);
}

/**
 * Generate a display name suggestion from email
 * Extracts the part before @ symbol
 */
export function generateDisplayNameFromEmail(email: string): string {
  const localPart = email.split("@")[0];

  // Clean up common patterns and make it more readable
  return localPart
    .replace(/[._-]/g, " ")
    .replace(/\b\w/g, (l) => l.toUpperCase())
    .trim();
}
